CREATE TABLE IF NOT EXISTS `PREFIX_dpd_shipment` (
  `id_dpd_shipment` INT(11) UNSIGNED AUTO_INCREMENT,
  `id_order` INT(11) UNSIGNED NOT NULL,
  `id_ws_manifest` INT(11) UNSIGNED,
  `id_contract` INT(11) UNSIGNED,
  `id_service` INT(11) UNSIGNED,
  `id_unique_service` INT(11) UNSIGNED,
  `id_pudo` VARCHAR(20) NOT NULL,
  `id_sender_address` INT(11) NOT NULL,
  `pl_number` VARCHAR(255) NOT NULL,
  `return_pl_number` VARCHAR(255) NOT NULL,
  `document_return_number` VARCHAR(255) NOT NULL,
  `is_document_return_enabled` TINYINT(1) NOT NULL,
  `pudo_country_code` VARCHAR(6) NOT NULL,
  `printed_label` TINYINT(1) UNSIGNED,
  `printed_manifest` TINYINT(1) UNSIGNED,
  `manifest_closed` TINYINT(1) UNSIGNED DEFAULT 0,
  `label_format` VARCHAR(255),
  `label_position` VARCHAR(255),
  `reference1` VARCHAR(255),
  `reference2` VARCHAR(255),
  `reference3` VARCHAR(255),
  `reference4` VARCHAR(255),
  `date_shipment` DATETIME,
  `date_print` DATETIME,
  `date_add` DATETIME,
  `date_upd` DATETIME,
  `pudo_address` VARCHAR(255) NOT NULL DEFAULT '',
  `saved` TINYINT(1) UNSIGNED DEFAULT 0,
  `num_of_parcels` INT(10) UNSIGNED,
  `weight` DECIMAL(20,2) UNSIGNED,
  `goods_price` DECIMAL(20,2) UNSIGNED,
  `is_test` TINYINT(1) UNSIGNED DEFAULT 0,
  PRIMARY KEY (`id_dpd_shipment`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
