name: Indexing and licensing
on: [pull_request]

jobs:
  autoindex:
    name: Adds index files
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout
          uses: actions/checkout@v4

      -   name: Cache vendor folder
          uses: actions/cache@v4
          with:
            path: vendor
            key: php-${{ hashFiles('composer.json') }}

      -   name: Cache composer folder
          uses: actions/cache@v4
          with:
            path: ~/.composer/cache
            key: php-composer-cache

      -   run: composer install --ignore-platform-reqs

      -   name: Run auto indexing
          run: php vendor/bin/autoindex

      -   uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: Adding auto indexes
            file_pattern: 'index.php */index.php'

  # Add license comments above code in every file
  license-addition:
    name: license addition
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout
          uses: actions/checkout@v4

      -   name: Cache vendor folder
          uses: actions/cache@v4
          with:
            path: vendor
            key: php-${{ hashFiles('composer.json') }}

      -   name: Cache composer folder
          uses: actions/cache@v4
          with:
            path: ~/.composer/cache
            key: php-composer-cache

      -   run: composer install --ignore-platform-reqs

      - name: Adding licenses
        run: vendor/bin/header-stamp --license=assets/afl.txt --exclude=vendor,node_modules

      -   uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: Automatic license addition applying
            file_pattern: ':!composer.lock :!composer.json'

